- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/verification-request.yml
- .github/workflows/verify.yml
DEVX-2070: Create a GitHub workflow
Created a skeleton for GitHub workflow, added issue template and code owners files.
> DEVX-2070: Create a GitHub workflow

- .github/ISSUE_TEMPLATE/verification-request.yml
- .github/workflows/verify.yml
Added validation of provided github and npm links, npm package installation on supported node.js versions, and tests passing.
https://jira.corp.adobe.com/browse/DEVX-2105
> DEVX-2105: Additional validation logic

- .github/workflows/add-template.yml
As published Adobe npm packages don't contain tests/won't contain them in the future, I switched to cloning the src code from provided GitHub repos in order to run npm tests.
Relates to DEVX-2105
> Switched to `git clone` for running npm tests

- .github/workflows/add-template.yml
I fixed job dependencies after switching to `git clone`.
Relates to DEVX-2105
> a fix after switching to `git clone`

- .github/ISSUE_TEMPLATE/remove-request.yml
- .github/workflows/remove-template.yml
- src/remove-from-registry.js
- src/validate-removal-author.js
DEVX-2106: Github workflow for removing templates from Template Registry
- implemented logic to remove a template from registry.json
- added checks:
- creator of remove-template issue must also have matching closed add-template issue for the same template (to ensure that only the original submitter of the template to the registry can have it removed)
- registry JSON file must exist in repository
- template is in registry
add-template workflow: #30
> DEVX-2106: Template Removal Workflow

- src/add-to-registry.js
- src/remove-from-registry.js
- src/validate-removal-author.js
> DEVX-2106: workflow for removing templates

- .github/workflows/add-template.yml
Fixed skipping the "fail-validation-comment" job on non-special comments.
Relates to DEVX-2105
> fixed skipping the "fail-validation-comment" job on non-special comments

- .github/workflows/add-template.yml
- package-lock.json
- package.json
- src/check-npm-package-metadata.js
Integrated our metadata validation package
Added a new "check-npm-package-metadata" validation job that uses https://www.npmjs.com/package/@adobe/aio-lib-template-validation
DEVX-2113
> DEVX-2113: Integrate validation library with GitHub actions

- .github/workflows/add-template.yml
Deleted unneeded step
DEVX-2113
> deleted uses: actions/setup-node@v2

- .github/workflows/remove-template.yml
> DEVX-2191: fix removal workflow

- .github/workflows/check-permissions-workflow.yml
- src/update-template.js
- Allow secrets.ADOBE_BOT_GITHUB_USERNAME to remove/update templates
- Updated src/update-template.js to reflect changes from https://github.com/adobe/aio-template-submission/pull/93
DEVX-2181
> DEVX-2181: Create scheduled jobs

- .github/workflows/add-template.yml
- .github/workflows/remove-template.yml
- .github/workflows/update-template.yml
A small fix for the concurrency issue that should decrease a probability of catching it.
https://jira.corp.adobe.com/browse/DEVX-2342
> DEVX-2342: Concurrency issue in Template Registry

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/check-permissions-workflow.yml
- .github/workflows/remove-template.yml
- .github/workflows/scheduled-template-registry-verification.yml
- .github/workflows/update-template.yml
- CONTRIBUTING.md
- src/check-registry.js
- src/github.js
- src/validate-request-author.js
- tests/github.test.js
- Updated `scheduled-template-registry-verification.yml` to avoid running it on forked repos
- Refactored setting `GITHUB_REPO_OWNER`, `GITHUB_REPO`
https://jira.corp.adobe.com/browse/DEVX-2363
https://jira.corp.adobe.com/browse/DEVX-2364
> Devx 2363 setup stage env (#358)

- .github/workflows/check-permissions-workflow.yml
- .github/workflows/remove-template.yml
- .github/workflows/update-template.yml
- package-lock.json
- package.json
- registry.json
- registry.schema.json
- src/add-to-registry.js
- src/is-admin.js
- src/npm-package-metadata.js
- src/update-template.js
- tests/add-to-registry.test.js
- tests/helper.js
- tests/is-admin.test.js
- tests/jest.setup.js
- tests/npm-package-metadata.test.js
- tests/templatePackage/install.yml
- tests/update-template.test.js
https://jira.corp.adobe.com/browse/DEVX-2366
npm test
> DEVX-2366: Multiple extension points support

- package-lock.json
- package.json
- tests/registry.test.js
> tests improvements

- src/githubIssueParser.js
https://jira.corp.adobe.com/browse/DEVX-2513
#166
> DEVX-2513: update parser to reflect Github issue template text change

- tests/__fixtures__/removalRequestIssuePayload.txt
- tests/__fixtures__/removalRequestIssuePayloadIncorrectNpmPackageName.txt
- tests/__fixtures__/reviewRequestIssuePayload.txt
- tests/__fixtures__/reviewRequestIssuePayloadIncorrectGithubRepoUrl1.txt
- tests/__fixtures__/reviewRequestIssuePayloadIncorrectGithubRepoUrl2.txt
- tests/__fixtures__/reviewRequestIssuePayloadIncorrectNpmPackageName.txt
- tests/__fixtures__/updateRequestIssuePayload.txt
- tests/__fixtures__/updateRequestIssuePayloadIncorrectNpmPackageName.txt
`npm run test` fails. Fix tests and test coverage.
> DEVX-2513-fix: fix tests

- .github/workflows/approve-template.yml
- .github/workflows/decline-template.yml
- .github/workflows/remove-template.yml
- .github/workflows/update-template.yml
A fix for DEVX-2526: Admins cannot approve/decline 3rd-party templates
DEVX-2526
- manually triggering Github workflow actions, and commenting them
> DEVX-2526: Admins cannot approve/decline 3rd-party templates - a fix

- .github/workflows/validate-template-workflow.yml
node 12 is obsolete, node 16 is supported by Adobe IO Runtime now, so we need to check templates against node 16
DEVX-2494
Manually checking running tests on the Template Registry side.
> DEVX-2494: Run tests against node 16

- .github/workflows/CI.yml
- .github/workflows/add-template.yml
- .github/workflows/approve-template.yml
- .github/workflows/check-permissions-workflow.yml
- .github/workflows/decline-template.yml
- .github/workflows/needs-more-verification.yml
- .github/workflows/remove-template.yml
- .github/workflows/scheduled-template-registry-verification.yml
- .github/workflows/update-template.yml
- .github/workflows/validate-template-workflow.yml
- src/check-github-link-package-name.js
- tests/check-github-link-package-name.test.js
- Add a validation that Github repo's package.json:name equals to the provided npm package name
- Improve executing `actions/checkout`
DEVX-2391
- npm test
- https://github.com/devx-services/aio-template-submission/issues/112
> DEVX-2391: Validate npm, Github repo package.json:name during submission

- .github/workflows/add-template.yml
- .github/workflows/approve-template.yml
- .github/workflows/update-template.yml
- .github/workflows/validate-template-workflow.yml
https://jira.corp.adobe.com/browse/DEVX-2616
When npm tests fail, the template is added or updated anyway, and no error message is created.
https://github.com/devx-services/aio-template-submission/issues/117
https://github.com/devx-services/aio-template-submission/actions/runs/3230805652
> DEVX-2616: fix check-npm-package matrix in validate-template

- .github/workflows/scheduled-template-registry-verification.yml
Fix dependency for daily builds
Daily builds are failing because of the wrong version.
Execute daily build.
> Fix dependency for scheduled workflow

- registry.json
> remove adobe recommended flag from beta templates

- src/github.js
- tests/github.test.js
Fixed issue text created by daily jobs. 
See https://github.com/adobe/aio-template-submission/pull/166
DEVX-2733: Package name validation fails
> DEVX-2733: Package name validation fails

- .github/workflows/CI.yml
- .github/workflows/add-template.yml
- .github/workflows/approve-template.yml
- .github/workflows/check-permissions-workflow.yml
- .github/workflows/decline-template.yml
- .github/workflows/needs-more-verification.yml
- .github/workflows/remove-template.yml
- .github/workflows/scheduled-template-registry-verification.yml
- .github/workflows/update-template.yml
- .github/workflows/validate-template-workflow.yml
- src/check-npm-package-metadata.js
- src/needs-more-verification.js
Provides fixes for found bugs.
https://jira.corp.adobe.com/browse/SITES-10416
- Manually checking Github workflows
> SITES-10416: Template registry workflow didn't indicate failure

- .github/workflows/CI.yml
- .github/workflows/add-template.yml
- .github/workflows/approve-template.yml
- .github/workflows/check-permissions-workflow.yml
- .github/workflows/decline-template.yml
- .github/workflows/needs-more-verification.yml
- .github/workflows/remove-template.yml
- .github/workflows/scheduled-template-registry-verification.yml
- .github/workflows/update-template.yml
- .github/workflows/validate-template-workflow.yml
A fix for SITES-12182
SITES-12182
Manually checking different scenarios.
> A fix for SITES-12182

- .github/workflows/add-template.yml
- .github/workflows/approve-template.yml
- .github/workflows/decline-template.yml
- .github/workflows/remove-template.yml
- .github/workflows/scheduled-template-registry-verification.yml
- .github/workflows/update-template.yml
Replaced abandoned dependency `ben-z/actions-comment-on-issue@1.0.2`.
This caused issues with comments.
See https://github.com/adobe/aio-template-submission/actions/runs/5880881132 or https://github.com/adobe/aio-template-submission/actions/runs/5879951814
> Fix for broken comment action

- .github/workflows/check-permissions-workflow.yml
- .github/workflows/needs-more-verification.yml
- .github/workflows/validate-template-workflow.yml
Fix recommended in `Remediation` section [here](https://securitylab.github.com/resources/github-actions-untrusted-input/).
Test the workflows by triggering the specific conditions, and using invalid/suspect inputs.
> fix: input validation in workflows
